### ISSUE TITLE
The length of Gaze vector

### ISSUE THREAD

**Issue by ZhanXKun** [yakhyo/gaze-estimation#11]
May I ask what determines the length of the arrows in the simulated gaze vectors? If it is related to depth information, is there a fixed calculation relationship between them?
Thx

**Comment by yakhyo** [comment]
Hi @ZhanXKun,
It's calculated according to the size bbox of face and gaze direction. It doesn't use any depth information. 

https://github.com/yakhyo/gaze-estimation/blob/a7b0217c448eea33637de95f7f22dc064c3a8e1f/utils/helpers.py#L108

**Comment by ZhanXKun** [comment]
Really thank you for your reply.
And one further question.the result of gaze estimation shows up with yaw and pitch. So may I ask whether the yaw and pitch angles are based on the Z-axis of the facial coordinate system or the camera coordinate system?

**Comment by yakhyo** [comment]
@ZhanXKun , as far as I know it's camera coordinate system.

**Comment by yakhyo** [comment]
@ZhanXKun , I am closing this issue, feel free to create a new one if there is any questions.
