### ISSUE TITLE
Example command for detect.py?

### ISSUE THREAD

**Issue by klvs** [yakhyo/gaze-estimation#12]
Sorry in advance if I'm misunderstanding how this repo is meant to be used.

I'm trying to run detect.py to get gaze estimation vectors. I'm not trying to train it. 

After downloading the weights into `./weights/` with `download.sh`  I tried to run the detect command like so:

`python ./detect.py --arch resnet50 --gaze-weights ./weights/resnet50.pt --face-weights ./weights/resnet50.pt --view --input ~/Downloads/test.mp4 --dataset mpiigaze`

This gives me an error:

```Namespace(arch='resnet50', gaze_weights='./weights/resnet50.pt', face_weights='./weights/resnet50.pt', view=True, input='/Users/alex/Downloads/test.mp4', output='output.mp4', dataset='mpiigaze', bins=28, binwidth=3, angle=42)
Failed to load the model: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./weights/resnet50.pt failed:Protobuf parsing failed.
INFO: Exception occured while loading pre-trained weights of face detection model. Exception: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./weights/resnet50.pt failed:Protobuf parsing failed.
INFO: Exception occured while loading pre-trained weights of gaze estimation model. Exception: Error(s) in loading state_dict for ResNet:
	size mismatch for fc_yaw.weight: copying a param with shape torch.Size([90, 2048]) from checkpoint, the shape in current model is torch.Size([28, 2048]).
	size mismatch for fc_yaw.bias: copying a param with shape torch.Size([90]) from checkpoint, the shape in current model is torch.Size([28]).
	size mismatch for fc_pitch.weight: copying a param with shape torch.Size([90, 2048]) from checkpoint, the shape in current model is torch.Size([28, 2048]).
	size mismatch for fc_pitch.bias: copying a param with shape torch.Size([90]) from checkpoint, the shape in current model is torch.Size([28]).
Traceback (most recent call last):
  File "/Users/alex/dev/gaze-estimation/./detect.py", line 157, in <module>
    main(args)
  File "/Users/alex/dev/gaze-estimation/./detect.py", line 114, in main
    bboxes, keypoints = face_detector.detect(frame)
UnboundLocalError: local variable 'face_detector' referenced before assignment
```

which implies that the face weights aren't set correctly.

I assumed that I don't need to download data since I'm not training it. Do I need to train it? Was it incorrect to assume that the model is not pre-trained? That seems to be the case. Or am I just running it incorrectly?

It appears that the data set pre-processing code for MPIIGaze isn't available should I want to train it.

Thank you for taking the time to read this issue. I appreciate any help I can get.

**Comment by klvs** [comment]
Ah thank you! That works!

**Comment by HafizNouman666** [comment]
> Hi @klvs ,
> 
> There is no need to train models, all model weights are provided. Models are trained on Gaze360 dataset. If you take a look at `detect.py` there are several optional variables, which means most of them has default variables. After downloading the model to `weights` folder, the command below should run as expected. There is a argument for `--dataset`, it is only for model settings only and by default it's `gaze360`.
> 
> In short, you should be able to run it using following command:
> 
> ```shell
> detect.py --arch resnet50 --gaze-weights weights/resnet50.pt --view --input ~/Downloads/test.mp4
> ```
> 
> If you have further questions, feel free to post.

hy when i run the file detect.py using this command it runs and generate output file for input video but stuck in terminal and not complete the processing @yakhyo 
![Screenshot from 2025-01-03 12-11-47](https://github.com/user-attachments/assets/c5999efb-22a5-4e83-9403-8bd614834f2a)

**Comment by yakhyo** [comment]
Hi @HafizNouman666 , it's working background to process the video. Maybe the video is longer and it will take to process all of them. You can visualize it and see the inference. Feel free to ask if you have further questions on a new issue.
