### ISSUE TITLE
Question about converting onnx

### ISSUE THREAD

**Issue by Choihyeonhwa** [yakhyo/gaze-estimation#13]
Hello.

I am currently trying to convert a trained .pt model to onnx.

I am getting the following error when importing the model and converting it to onnx.

I think the model structure and the actual trained model structure are different. Can you check it?

RuntimeError: Error(s) in loading state_dict for ResNet:
size mismatch for fc_yaw.weight: copying a param with shape torch.Size([90, 512]) from checkpoint, the shape in current model is torch.Size([1000, 512]).
size mismatch for fc_yaw.bias: copying a param with shape torch.Size([90]) from checkpoint, the shape in current model is torch.Size([1000]). size mismatch for fc_pitch.weight: copying a param with shape torch.Size([90, 512]) from checkpoint, the shape in current model is torch.Size([1000, 512]).
 size mismatch for fc_pitch.bias: copying a param with shape torch.Size([90]) from checkpoint, the shape in current model is torch.Size([1000]).

I'll show you the code I used.

import torch
import torch.onnx
from model import resnet18

model_path = "D:/neudive/pythonProject1/resnet18.pt"
onnx_output_path = "D:/neudive/pythonProject1/resnet18.onnx"

model = resnet18()
model.load_state_dict(torch.load(model_path, map_location="cpu"))
model.eval()

dummy_input = torch.randn(1, 3, 224, 224)

torch.onnx.export(
 model,
 dummy_input,
 onnx_output_path,
 export_params=True;
 opset_version=11;
 input_names=["input"],
 output_names=["output"],
 dynamic_axes={
 "input": {0: "batch_size"},
 "output": {0: "batch_size"}
 }
)

print(onnx_output_path)

**Comment by yakhyo** [comment]
hi @Choihyeonhwa , model initialization requires additional config #bins and number of bins depends on the dataset config that the model trained on. 

Please take look at inference code and model initialization. -> https://github.com/yakhyo/gaze-estimation/blob/main/detect.py#L80

**Comment by Choihyeonhwa** [comment]
I downloaded and used resnet18.pt from the github main page, so how should I change the code?

**Comment by yakhyo** [comment]
@Choihyeonhwa , when you initialize the model `model = resnet18()` please pass required params to it then load the pre-trained model weights.

**Comment by yakhyo** [comment]
I think it should work in that way also. But I would recommend simply initialize the model by `model = resnet18(pretrained=False, num_classes=bins)` then load state_dict. 

If you want to add some additional functionality then wrapping it with custom class would be better, imho.

**Comment by Choihyeonhwa** [comment]
Thank you for your kind reply.
