### ISSUE TITLE
Pre-trained weghts not found

### ISSUE THREAD

**Issue by Sadat75** [yakhyo/gaze-estimation#8]
Dear @yakhyo,

Thank you for the code. I was unable to download the pre-trained weights of mobileone_s2, mobileone_s3, mobileone_s4.
Could you please provide the link to these weights?

Thank you.

**Comment by yakhyo** [comment]
Hi @Sadat75 , thank you for your interest.

Unfortunately, Due to limited computing resources I had,  I could not train all of the models from mobileone family. I trained only `mobileone_s0` version. However, you can easily train those models from scratch using this repo. 

thank you

**Comment by Sadat75** [comment]
Dear @yakhyo,

Thank you for the quick response. I will train the models.
Thank you!
